#! /usr/bin/python3
# list files on Toshiba FlashAir SD card via wi-fi
# see https://www.flashair-developers.com/en/documents/api/

import os
import sys
import argparse
import requests
import configparser


def fmt(size):
    kb=size/1024
    mb=size/1048576
    gb=size/1073741824
    s='{:,.3f} GB'.format(gb)
    if gb < 1:
        s='{:,.3f} MB'.format(mb)
    if mb < 1:
        s='{:,.3f} KB'.format(kb)
    return s

config_file=os.path.expanduser('~/.flashair')
config=configparser.ConfigParser()
config.read(config_file)
def_address=config['DEFAULT'].get('address', None)
def_directory=config['DEFAULT'].get('directory', '/')

parser=argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-a', '--address', help='card network address', default=def_address)
parser.add_argument('-d', '--directory', help='directory', default=def_directory)
args=parser.parse_args()
address=args.address
dir=args.directory

if address == None:
    print('you must supply a network address for the card')
    exit(1)

# if values have changed, write them back as defaults
if address != def_address or dir != def_directory:
    config['DEFAULT']['address']=address
    config['DEFAULT']['directory']=dir
    with open(config_file, 'w') as f:
        config.write(f)

# no leading or trailing slashes in directory
if dir and dir[0] == '/':
    dir=dir[1:]
if dir and dir[-1] == '/':
    dir=dir[:-1]

r=requests.get('http://'+address+'/command.cgi?op=100&DIR=/'+dir)
if not r:
    if r.status_code == 404:
        print('no such directory:', dir)
    else:
        print('error', r.status_code)
    sys.exit(1)

sum=0
output=[]
for line in r.text.split()[1:]:
    # this code has to handle commas in file name and directory name. in data that's comma-delimited
    first, size, attrib, date, time=line.rsplit(',', 4)
    if not dir:
        file=first[1:]
    else:
        file=first[len(dir)+2:]

    attrib=int(attrib)
    if attrib & 16:
        # this is a directory
        output.append((file, '<DIR>', ''))
    else:
        # this is a file
        # comma-formatted number
        size=int(size)
        kb=size/1024
        mb=size/1048576
        gb=size/1073741824
        output.append((file, '{:,}'.format(size), fmt(size)))
        sum+=size

if not dir:
    dir='/'
if len(output) == 0:
    print('directory "'+dir+'" is empty')
    raise SystemExit

# sort alphabetically
output.sort(key=lambda x: x[0])

# grab remaining space
r=requests.get('http://'+address+'/command.cgi?op=140')
t=r.text.split('/')
empty=int(t[0])
total, sector=map(int, t[1].split(','))
empty*=sector
total*=sector
used=total-empty
space=empty
pct_used=(used/total)*100.0
pct_empty=(empty/total)*100.0

# add totals
output.append(('Dir Total:', '{:,}'.format(sum), fmt(sum)))
output.append(('Used:', '{:,}'.format(used), fmt(used), '{:.2f}%'.format(pct_used)))
output.append(('Unused:', '{:,}'.format(space), fmt(space), '{:.2f}%'.format(pct_empty)))

# print in neat columns
width1=max(len(x[0]) for x in output)
width2=max(len(x[1]) for x in output)
width3=max(len(x[2]) for x in output)
width4=max(len(x[3]) for x in output if len(x) > 3)
output.insert(-3, ('-'*width1, '-'*width2, '-'*width3))
print('Directory:', dir)
for data in output:
    if len(data) == 3:
        print('{0:{1}} {2:>{3}} {4:>{5}}'.format(data[0], width1,
                                                 data[1], width2,
                                                 data[2], width3))
    else:
        print('{0:{1}} {2:>{3}} {4:>{5}} {6:>{7}}'.format(data[0], width1,
                                                          data[1], width2,
                                                          data[2], width3,
                                                          data[3], width4))
