#!/usr/bin/env python3
# delete files from Toshiba FlashAir SD card via wi-fi
# see https://www.flashair-developers.com/en/documents/api/

import os
import sys
import fnmatch
import argparse
import requests
import configparser
import flashair

def match(s):
    if s in card.args.files:
        return True
    for arg in card.args.files:
        if fnmatch.fnmatch(s, arg):
            return True
    return False

card=flashair.card()
card.parser.add_argument('files', nargs='+', help='files/directories to delete', default=None)
card.parser.add_argument('-i', '--interactive', help='prompt before every removal', default=False, action='store_true')
card.setup()
card.get_files()
if len(card.files) == 0:
    print('no files to delete in', dir)
    sys.exit(1)

# keep the host from writing during changes
requests.get('http://'+card.address+'/upload.cgi?WRITEPROTECT=ON')

# delete matching files
for file, size, attrib in card.files:
    if match(file):
        if card.args.interactive:
            if attrib & 16:
                choice=input("remove directory '"+file+"'? ")
            else:
                choice=input("remove regular file '"+file+"'? ")
            if choice[0].lower() != 'y':
                continue
        r=requests.get('http://'+card.address+'/upload.cgi?DEL='+card.dir+file)
        if r.text != 'NG':
            print(file, 'deleted')
        else:
            print('unable to delete', file)

# re-enable disk
requests.get('http://'+card.address+'/upload.cgi?WRITEPROTECT=OFF')
