#! /usr/bin/python3
# delete files from Toshiba FlashAir SD card via wi-fi
# see https://www.flashair-developers.com/en/documents/api/

import sys
import fnmatch
import requests

def match(s):
    args=sys.argv[1:]
    if not args:
        return True
    if s in args:
        return True
    for arg in args:
        if fnmatch.fnmatch(s, arg):
            return True
    return False

ip='flashair'

# get files on card
files=[]
r=requests.get('http://'+ip+'/command.cgi?op=100&DIR=/')
if not r:
    print('communications error', r.status_code)
    sys.exit(1)
for line in r.text.split():
    # this code assumes no commas in directory name or file name
    fields=line.split(',')
    if len(fields) != 6:
        continue
    dir, file, size, attrib, date, time=fields
    files.append((file, int(attrib)))

if not files:
    print('no files to delete')
    sys.exit(1)

# keep the host from writing during changes
requests.get('http://'+ip+'/upload.cgi?WRITEPROTECT=ON')

# delete matching files
for file in files:
    fn, attrib=file
    if match(fn):
        r=requests.get('http://'+ip+'/upload.cgi?DEL=/'+fn)
        if r.text != 'NG':
            print(fn, 'deleted')
        else:
            print('unable to delete', fn)

# re-enable disk
requests.get('http://'+ip+'/upload.cgi?WRITEPROTECT=OFF')
