#! /usr/bin/env python3
# display tree of files on Toshiba FlashAir SD card via wi-fi
# see https://www.flashair-developers.com/en/documents/api/

import os
import sys
import argparse
import requests
import configparser
import flashair

def tree(dir, pad):
    card.dir=dir
    card.get_files()
    files=card.files
    files.sort(key=lambda x: x[0])
    ctr=len(files)
    for file, size, attrib, date in files:
        ctr-=1
        if ctr:
            print(pad[2:]+'├─', file)
        else:
            print(pad[2:]+'└─', file)
        if attrib & 16:
            if dir == '/':
                dir=''
            if ctr:
                tree(dir+'/'+file, pad+'│  ')
            else:
                tree(dir+'/'+file, pad[:-2]+'     ')

card=flashair.card()
card.setup()
tree('/', '  ')
